name: new_face_authenticator
description: Flutter plugin cross-platform (iOS, Android) for Combate à Fraude's FaceAuthenticator (https://github.com/combateafraude).
version: 4.0.0
homepage: https://www.combateafraude.com/
repository: https://github.com/combateafraude/Flutter/tree/master/packages/new_face_authenticator

environment:
  sdk: ">=2.12.0 <4.0.0"
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.caf.face_authenticator
        pluginClass: FaceAuthenticatorPlugin
      ios:
        pluginClass: FaceAuthenticatorPlugin
